version: '3.7'
services:
  web:
    build: ./web/
    image: wsgi:hacker_news
    hostname: hn_wsgi
    container_name: hn_wsgi
    networks: 
      local_network:
        ipv4_address: 172.22.0.2
    depends_on:
      - postgres
      - redis
    volumes:
      - ./web/celery/log:/tmp/celery.log
      - ./web/log:/var/log/gunicorn
      - /var/www/hacker_news/web/src/hacker_news:/var/www/hacker_news
      - ./web/init/gunicorn.py:/etc/gunicorn/gunicorn.py

  nginx:
    image: nginx:latest
    hostname: hn_nginx
    container_name: hn_nginx
    network_mode: host
    depends_on:
      - web
    volumes:
      - ./nginx/log:/var/log/nginx
      - /var/www/hacker_news/web/src/hacker_news:/var/www/hacker_news
      - ./nginx/init/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:8000" 

  postgres:
    build: ./postgres/
    image: postgres:hacker_news
    hostname: hn_postgres
    container_name: hn_postgres
    networks: 
      local_network: 
        ipv4_address: 172.22.0.3 
    volumes:
      - hacker_news_pgdata:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/log:/log

  redis:
    build: ./redis/
    image: redis:hacker_news
    hostname: hn_redis
    container_name: hn_redis
    networks:
      local_network:
        ipv4_address: 172.22.0.4
    volumes:
      - ./redis/log:/log
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/redis/redis.conf

networks:
  local_network:
    ipam:
      driver: default
      config: 
        - subnet: "172.22.0.0/24"
volumes:
  hacker_news_pgdata: 
