# Generated by Django 2.2.7 on 2019-12-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updater', '0002_auto_20191201_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
